site_name: KAMISHIBAI
site_url: https://purple-ocean-0e8c70a00.6.azurestaticapps.net/
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.prune
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - stylesheets/extra.css

plugins:
  - awesome-pages
  - search:
      lang: ja
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      indexing: 'full'