site_name: KAMISHIBAI
site_url: https://purple-ocean-0e8c70a00.6.azurestaticapps.net/
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.prune
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - stylesheets/extra.css

plugins:
  - awesome-pages
  - search:
      prebuild_index: true  # 事前ビルドによる高速化
      min_search_length: 2  # 最小検索文字数を2文字に設定
      lang: ja
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      indexing: 'sections'  # セクション単位のインデックス作成
      search_index_only: false  # 完全なテキストも保存