# ワークフローの名前（GitHub Actionsダッシュボードに表示される）
name: Azure Static Web Apps CI/CD

# このワークフローがいつ実行されるかを定義
on:
  push:
    branches:
      - main  # mainブランチへのプッシュ時に実行
  pull_request:
    types: [opened, synchronize, reopened, closed]  # PR作成・更新・再オープン・クローズ時に実行
    branches:
      - main  # mainブランチに対するPRの場合に実行

permissions:
  contents: read
  pull-requests: write  # PRへのコメント権限を追加

# 実行するジョブを定義
jobs:
  # ビルドとデプロイを行うジョブ
  build_and_deploy_job:
    # このジョブを実行する条件：pushイベント、またはPRがクローズ以外のアクション時
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest  # Ubuntu最新バージョンの仮想環境で実行
    name: Build and Deploy Job  # ジョブの表示名
    steps:
      # ステップ1: リポジトリのコードをチェックアウト
      - uses: actions/checkout@v3  # GitHubのチェックアウトアクションv3を使用
        with:
          submodules: true  # サブモジュールも含めてチェックアウト（必要な場合）
          lfs: false  # Git LFS（Large File Storage）は使用しない
          
      # ステップ2: Pythonの実行環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4  # Python環境セットアップアクションv4を使用
        with:
          python-version: '3.x'  # 最新の安定版Python 3系を使用
          
      # ステップ3: MkDocsと必要なプラグイン・拡張機能をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # pipを最新バージョンにアップグレード
          pip install mkdocs-material  # Material for MkDocsテーマをインストール
          pip install mkdocs  # MkDocs本体をインストール
          pip install mkdocs-awesome-pages-plugin  # ナビゲーション構造のカスタマイズ用プラグイン
          pip install pymdown-extensions  # Markdown拡張機能（コードハイライト、タブなど）をインストール
          
      # ステップ4: MkDocsでサイトを初回ビルド
      - name: First MkDocs Build
        run: mkdocs build  # mkdocs.ymlの設定に基づいてサイトを生成（デフォルトでは/siteディレクトリに出力）
        
      # ステップ5: docs\画面遷移 フォルダを削除
      - name: Remove docs\画面遷移 folder
        run: |
          rm -rf "docs/画面遷移"
          echo "「docs/画面遷移」フォルダを削除しました"
          
      # ステップ6: site-exportフォルダへの2回目のビルド
      - name: Second MkDocs Build to site-export
        run: |
          # site-exportという出力先を指定してビルド
          mkdocs build -d site-export
          echo "site-exportフォルダにビルドしました"
          
      # ステップ7: site-exportをZIP化してsiteフォルダにコピー
      - name: Create ZIP and copy to site folder
        run: |
          # site-exportフォルダをZIP化
          cd site-export
          zip -r ../site-export.zip .
          cd ..
          
          # siteフォルダにZIPファイルをコピー
          mkdir -p site
          cp site-export.zip site/
          echo "site-exportフォルダをZIP化し、siteフォルダにコピーしました"
          
          # 確認のためにファイル一覧を表示
          echo "site フォルダの内容:"
          ls -la site/
        
      # ステップ8: ビルドしたサイトをAzure Static Web Appsにデプロイ
      - name: Build And Deploy
        id: builddeploy  # このステップのID（後続のステップから参照可能）
        uses: Azure/static-web-apps-deploy@v1  # Azure Static Web Appsデプロイアクションv1を使用
        with:
          # Azure Static Web Appsのデプロイトークン（GitHubシークレットから取得）
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_OCEAN_0E8C70A00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub APIトークン（PR連携など用、自動設定）
          action: "upload"  # 実行するアクション（uploadはコンテンツをデプロイ）
          
          # アプリケーション設定（Azure Static Web Appsのビルド設定）
          app_location: "/site"  # MkDocsがビルドした静的サイトのディレクトリパス
          api_location: ""  # APIのソースディレクトリ（使用しない場合は空）
          output_location: ""  # ビルド出力先（既にビルド済みのため空に設定）
          skip_app_build: true  # MkDocsで既にビルド済みのため、Azure側でのビルドプロセスをスキップ

  # プルリクエストがクローズされたときに実行するジョブ
  close_pull_request_job:
    # このジョブを実行する条件：PRがクローズされた場合のみ
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest  # Ubuntu最新バージョンの仮想環境で実行
    name: Close Pull Request Job  # ジョブの表示名
    steps:
      # PRに関連するステージング環境を削除するステップ
      - name: Close Pull Request
        id: closepullrequest  # このステップのID
        uses: Azure/static-web-apps-deploy@v1  # Azure Static Web Appsデプロイアクションv1を使用
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_OCEAN_0E8C70A00 }}
          action: "close"  # クローズアクション（PRに関連するステージング環境を削除）